#!/bin/bash

. ../src/bash_arg_parser

BAP_new_command 'fooBar'
BAP_set_top_level_cmd_name 'genkey'
BAP_add_required_short_opt 'genkey' 'o' 'output_dir'
BAP_add_optional_short_opt 'genkey' 'c' 'x509_config'
BAP_generate_parse_func 'genkey'

# Helper funcs
pv() {
    local var=$1
 
    echo "$var is '${!var}'"
}

genkey() {
    local get_args
    get_args=$(parse_genkey_args "$@") || exit
    eval "$get_args"
    
    pv output_dir
    pv x509_config
}

genkey "$@"
