#!/bin/bash

. ../src/bash_arg_parser

BAP_new_command 'genkey'
#BAP_set_top_level_cmd_name 'genkey' 'titanium-modsign'
BAP_add_optional_short_opt 'genkey' 'x' 'x509_config'
BAP_add_required_short_opt 'genkey' 'c' 'foo'
BAP_set_opt_arg_type 'genkey' 'bar' 'efe'
BAP_generate_parse_func 'genkey'

type parse_genkey_args

# Helper funcs
pv() {
    local var=$1
 
    echo "$var is '${!var}'"
}

genkey() {
    local get_args
    get_args=$(parse_genkey_args "$@") || exit
    eval "$get_args"
    
 #   pv output_dir
    pv x509_config
}

genkey "$@"
