#!/bin/bash

set -u

. ../src/bash_arg_parser

BAP_new_command 'santa'
BAP_set_top_level_cmd_name 'santa' 'greet'
BAP_add_optional_short_opt 'santa' 'w' 'whom' 'The person whom santa should greet.'
BAP_create_help_option 'santa'
BAP_generate_parse_func 'santa'

BAP_new_command 'mom'
BAP_set_top_level_cmd_name 'mom' 'greet'
BAP_add_required_short_opt 'mom' 'w' 'whom'
BAP_create_help_option 'mom'
BAP_generate_parse_func 'mom'

mom() {
    local get_args
    get_args=$(parse_mom_args "$@") || exit
    eval "$get_args"
 
    echo "Mom loves you, ${whom}!"
    echo "Remaining arguments: $@"
}

santa() {
    local get_args
    get_args=$(parse_santa_args "$@") || exit
    eval "$get_args"
    
    if [ -z "$whom" ]; then
        echo "Santa is sad and alone since there is noone to greet. You are a monster."
    else
        echo "Santa put $whom on his naughty list!"
    fi

    echo "Remaining arguments: $@"
}

BAP_generate_top_level_cmd_parser 'greet'

parse_top_level_args "$@"
