#!/bin/bash

. ../src/bash_arg_parser

BAP_new_command 'genkey'
BAP_set_top_level_cmd_name 'genkey' 'titanium-modsign'
BAP_add_required_short_opt 'genkey' 'o' 'output_dir' 'Output directory.'
BAP_add_optional_short_opt 'genkey' 'c' 'x509_config'
BAP_create_help_option 'genkey'
BAP_generate_parse_func 'genkey'

# Let's view the resuling parser function!
type parse_genkey_args

# Helper funcs
pv() {
    local var=$1
 
    echo "$var is '${!var}'"
}

genkey() {
    local get_args
    get_args=$(parse_genkey_args "$@") || exit
    eval "$get_args"
    
    pv output_dir
    pv x509_config
}


genkey "$@"
