#!/bin/bash

set -eu


declare -gr __bash_parse_add_short_opt_usage="Usage is '\${FUNCNAME[0]} <command> <opt_letter> <opt_name>'"

declare -ga __bash_parse_cmd_functions_to_export=(__bash_parse_die __bash_parse_die_required_arg __bash_parse_check_opt_arg __bash_parse_die_file_must_exist)
declare -ga __bash_parse_cmd_variables_to_export=()
declare -ga __bash_parse_cmd_opt_help=()

####################################################################
# Private function which are called by functions in the Public API #
####################################################################

__bash_parse_die() {
    echo -e "$@" >&2
    exit 1
}

__bash_parse_die_required_arg() {
    local arg_name=$1
    local usage_text=$2

    echo "fatal: $arg_name required." >&2
    __bash_parse_die "Usage: $usage_text"
}

__bash_parse_die_file_must_exist() {
    local file_name=$1
    local usage_text=$2

    echo "fatal: file '$file_name' does not exist." >&2
    __bash_parse_die "Usage: $usage_text"
}

__bash_parse_check_opt_arg() {
    local arg=${1}

    # don't let it be empty or start with a '-',
    # because that is probably an option flag
    [ -n "${arg}" ] && ! [[ "${arg}" = -* ]]
}

#####################
# Private functions #
#####################

__bash_parse_check_valid_bash_var_name() {
	local bash_var_name=$1
	local re='^[_a-zA-Z][_a-zA-Z0-9]*$'
	[[ "$bash_var_name" =~ $re ]]
}

__bash_parse_assert_defined() {
    local cmd_name=$1
    local func_that_should_have_been_called=$2
    local funcname=$3

    #BASH_LINENO[second from last] is the line number
    #of the caller of the public api
    if ! [ -v "$cmd_name" ]; then
        __bash_parse_die "$0: line ${BASH_LINENO[${#BASH_LINENO[@]} - 2]}: ($funcname) must call '$func_that_should_have_been_called' first to define command '${cmd_name##__bash_parse_cmd_}'"
    fi
}

__bash_parse_assert_short_opt() {
    local character=$1
    local funcname=$2

    if ! [ ${#character} -eq 1 ]; then
        __bash_parse_die "$0: line ${BASH_LINENO[2]}: ($funcname) must only provide a single letter for the short opt letter argument!\nOffending argument: '$character'"
    fi
}

__bash_parse_add_opt() {
    local expected_number_of_args=5
    if [ $# -eq "$expected_number_of_args" ]; then
        local cmd_name=$1
        local opt_letter=$2
        local opt_name=$3
        local opt_required_or_optional=$4
        local funcname=$5
        local help_text=
    else
        __bash_parse_die "INTERNAL ERROR! Wrong number of args passed to '${FUNCNAME[0]}'. Should be $expected_number_of_args, but got $#"
    fi

    __bash_parse_assert_defined "__bash_parse_cmd_$cmd_name" 'BAP_new_command()' "$funcname"
    __bash_parse_assert_short_opt "$opt_letter" "$funcname"
    if ! __bash_parse_check_valid_bash_var_name "$opt_name"; then
        __bash_parse_die "$0: line ${BASH_LINENO[1]}: ($funcname) must provide a valid Bash variable name for parameter <opt_name>\nOffending argument: '$opt_name'"        
    fi
    
    opt_letter=$(printf "%q" "$opt_letter")

    eval "__bash_parse_cmd_${cmd_name}_opts+=(\"\$opt_letter\" \"\$opt_name\" $opt_required_or_optional none)"
    __bash_parse_cmd_opt_help+=("$opt_letter" '')
}

__bash_parse_get_opt_help_text() {
    local opt_letter=$1
    
    for ((i = 0; i < ${#__bash_parse_cmd_opt_help[@]}; i += 2)); do
        local letter=${__bash_parse_cmd_opt_help[i]}

        if [ "$letter" = "$opt_letter" ]; then
            echo "${__bash_parse_cmd_opt_help[i + 1]}"
            return 0
        fi
    done
}

__bash_parse_set_opt_help_text() {
    local opt_letter=$1
    local opt_help_text=$2
    local funcname=$3


    for ((i = 0; i < ${#__bash_parse_cmd_opt_help[@]}; i += 2)); do
        local letter=${__bash_parse_cmd_opt_help[i]}

        if [ "$letter" = "$opt_letter" ]; then
            __bash_parse_cmd_opt_help[i + 1]=$opt_help_text
            return 0
        fi
    done

    __bash_parse_die "$0: line ${BASH_LINENO[1]}: ($funcname) must call 'BAP_add_optional_short_opt()' or 'BAP_add_required_short_opt()' to define option '$opt_letter'"
}

__bash_parse_get_all_opt_help_text() {
    for ((i = 0; i < ${#__bash_parse_cmd_opt_help[@]}; i += 2)); do
        local letter=${__bash_parse_cmd_opt_help[i]}
        local help_text=${__bash_parse_cmd_opt_help[i + 1]}
    
        [ -n "$help_text" ] && echo "  -$letter    $help_text"
    done
}

__bash_parse_opt_is_defined() {
    local cmd_name=$1
    local opt_name=$2

    eval "declare -n short_opt_array=__bash_parse_cmd_${cmd_name}_opts"
    # Var is set in eval
    # shellcheck disable=SC2154
    for ((i = 0; i < ${#short_opt_array[@]}; i += 4)); do
        local opt_text=${short_opt_array[i + 1]}
        [ "$opt_text" = "$opt_name" ] && return 0
    done
    return 1
}

__bash_parse_opt_set_arg_type() {
    local cmd_name=$1
    local opt_name=$2
    local opt_arg_type=$3

    eval "declare -n short_opt_array=__bash_parse_cmd_${cmd_name}_opts"
    # Var is set in eval
    # shellcheck disable=SC2154
    for ((i = 0; i < ${#short_opt_array[@]}; i += 4)); do
        local opt_text=${short_opt_array[i + 1]}
        if [ "$opt_text" = "$opt_name" ]; then
            short_opt_array[i + 3]=$opt_arg_type
            return
        fi
    done
}

##############
# Public API #
##############

BAP_generate_parse_func() {
    [ $# -ne 1 ] && __bash_parse_die "$0: line ${BASH_LINENO[0]}: Usage is 'BAP_generate_parse_func <command>'"
    local name_of_command=$1

    __bash_parse_assert_defined "__bash_parse_cmd_$name_of_command" 'BAP_new_command()' "${FUNCNAME[0]}"

    local sub_cmd_name=$name_of_command
    local script=""
    local script_locals=""
    local eval_ret=""
    local getopts_str=":"
    local getopts_case_body=""
    local getopts_case_colon_body=""
    local check_for_req_args_body=""
    local check_opt_arg_type=""
    local add_dash_h=""
    local usage_text="$sub_cmd_name\$add_dash_h"
    local required_argument_given=no
    local opts_help_text=""
    
    eval "local top_level_cmd=\"\$__bash_parse_cmd_${name_of_command}_top_level_cmd_name \""
    [ "$top_level_cmd" = " " ] && top_level_cmd=

    eval "declare -n short_opt_array=__bash_parse_cmd_${name_of_command}_opts"

    # Var is set in eval
    # shellcheck disable=SC2154
    for ((i = 0; i < ${#short_opt_array[@]}; i += 4)); do
        local opt_letter=${short_opt_array[i]}
        local opt_text=${short_opt_array[i + 1]}
        local opt_type=${short_opt_array[i + 2]}
        local opt_arg_type=${short_opt_array[i + 3]}
        local opt_help_text
       
        opt_help_text=$(__bash_parse_get_opt_help_text "$opt_letter")
        [ -n "$opt_help_text" ] && opts_help_text+="  -$opt_letter    $opt_help_text"
      
        script_locals+="local __var_$opt_text=; "
        eval_ret+="local $opt_text='\$__var_$opt_text'; "
        getopts_str+="$opt_letter:"
        getopts_case_body+="$opt_letter) __var_$opt_text=\$OPTARG; "
        getopts_case_body+="__bash_parse_check_opt_arg \"\$__var_$opt_text\" || "
        getopts_case_body+="__bash_parse_die_required_arg '<$opt_text>' \"$top_level_cmd\$USAGE_TEXT_$sub_cmd_name\";; "

        getopts_case_colon_body+="$opt_letter) "
        getopts_case_colon_body+="__bash_parse_die_required_arg '<$opt_text>' \"$top_level_cmd\$USAGE_TEXT_$sub_cmd_name\";; "

        case "$opt_type" in
            required) 
                required_argument_given=yes
                usage_text+=" -$opt_letter <$opt_text>"

                check_for_req_args_body+="[ -z \"\$__var_$opt_text\" ] && "
                check_for_req_args_body+="__bash_parse_die_required_arg '<$opt_text>' \"$top_level_cmd\$USAGE_TEXT_$sub_cmd_name\"; "
                ;;
            optional)
                usage_text+=" [-$opt_letter <$opt_text>]"
                ;;
            *)
                __bash_parse_die "INTERNAL ERROR: (${FUNCNAME[0]}) invalid opt_type of '$opt_type'"
                ;;
        esac
        case "$opt_arg_type" in
            none)
                ;;
            existent_file)
                if [ "$opt_type" = optional ]; then
                    check_opt_arg_type+="if [ -n \"\$__var_$opt_text\" ]; then [ -e \"\$__var_$opt_text\" ] || "
                    check_opt_arg_type+="__bash_parse_die_file_must_exist \"\$__var_$opt_text\" \"$top_level_cmd\$USAGE_TEXT_$sub_cmd_name\"; fi; "
                else
                    check_opt_arg_type+="[ -e \"\$__var_$opt_text\" ] || "
                    check_opt_arg_type+="__bash_parse_die_file_must_exist \"\$__var_$opt_text\" \"$top_level_cmd\$USAGE_TEXT_$sub_cmd_name\"; "
                fi
                ;;
            *)
                __bash_parse_die "INTERNAL ERROR: (${FUNCNAME[0]}) invalid opt_type of '$opt_arg_type'"
                ;;
        esac
    done

    # Now construct the usage text declaration, 
    # the parser function definition,
    # and the body of the function

    # It'll look something like:

    : << EOM
    declare -r USAGE_TEXT_foo=...
    parse_foo_args() {
        local arg_a=
        local arg_b=
        while getopts ':a:b:' opt; do
            case \$opt in
                a)
                    a=\$OPTARG
                    make_sure_var_exists
                ...
                :)
                    handle cases where no arg was given to an option
        done

        handle_making_sure_we_got_all_required_args
    }
EOM
        
    # Remeber that you can use the 'type' command
    # in your program after calling 'BAP_generate_parser()'
    # to have Bash pretty-print the resuling function`
    # if you are curious :)
    # see examples/type_example

    eval_ret+="shift \$((OPTIND - 1)); "
    
    local name_of_usage_text_variable="USAGE_TEXT_$sub_cmd_name"
    local name_of_opt_usage_text_variable="OPT_USAGE_TEXT_$sub_cmd_name"

    if [ -n "$opts_help_text" ]; then
        # Var is used in eval of $usage_text
        # shellcheck disable=SC2034
        add_dash_h=' -h'
        getopts_str+='h'
        getopts_case_body+="h) __bash_parse_die \"Usage: $top_level_cmd\$$name_of_usage_text_variable"
        getopts_case_body+=$'\n\n'"Options: "$'\n'"\$$name_of_opt_usage_text_variable"
        getopts_case_body+="\" ;; "
    fi

    eval "script+=\"declare -gr \$name_of_usage_text_variable=\\\"$usage_text\\\"; \""
    # May or may not be empty
    script+="declare -gr $name_of_opt_usage_text_variable=\"$opts_help_text\"; "

    local name_of_generated_func="parse_${sub_cmd_name}_args"

    script+="$name_of_generated_func() { "
    script+=$script_locals

    if [ "$required_argument_given" = yes ]; then
        script+="[ \$# -eq 0 ] && __bash_parse_die \"Usage: $top_level_cmd\$USAGE_TEXT_$sub_cmd_name\"; "
    fi
    script+="while getopts '$getopts_str' opt; do case \$opt in "
    script+=$getopts_case_body 
    script+=":) case \$OPTARG in $getopts_case_colon_body esac;; "
    script+="\\?) __bash_parse_die \"Unsupported option: -\$OPTARG\";; esac; done; "
    script+=$check_for_req_args_body
    script+=$check_opt_arg_type
    script+="echo \"$eval_ret\"; "
    script+="}"

    __bash_parse_cmd_functions_to_export+=("$name_of_generated_func")
    __bash_parse_cmd_variables_to_export+=("$name_of_usage_text_variable" "$name_of_opt_usage_text_variable")
    eval "$script"
}

BAP_new_command() {
    local usage="Usage is '${FUNCNAME[0]} <new_command>'"
    [ $# -ne 1 ] && __bash_parse_die "$0: line ${BASH_LINENO[0]}: $usage"
    local cmd_name=$1
	
	if ! __bash_parse_check_valid_bash_var_name "$cmd_name"; then
        __bash_parse_die "$0: line ${BASH_LINENO[0]}: must provide a valid Bash variable name for parameter <new_command>\nOffending argument: '$cmd_name'"
    fi

    # Just define this variable
    declare -gr __bash_parse_cmd_"${cmd_name}"=
    declare -g __bash_parse_cmd_"${cmd_name}"_top_level_cmd_name=
    declare -g __bash_parse_cmd_"${cmd_name}"_opts_help_text=
    eval "declare -g __bash_parse_cmd_${cmd_name}_opts=()"
}

BAP_set_top_level_cmd_name() {
    local usage="Usage is '${FUNCNAME[0]} <command> <top level cmd name>'"
    [ $# -ne 2 ] && __bash_parse_die "$0: line ${BASH_LINENO[0]}: $usage"
    local cmd_name=$1
    # Var is used in eval
    # shellcheck disable=SC2034
    local top_level_cmd_name=$2
    
    local top_level_cmd_name_hash
    
    __bash_parse_assert_defined "__bash_parse_cmd_$cmd_name" 'BAP_new_command()' "${FUNCNAME[0]}"
    
    eval "__bash_parse_cmd_${cmd_name}_top_level_cmd_name=\$top_level_cmd_name"

    # We need to hash the name to create a valid Bash variable name in case of invalid characters
    top_level_cmd_name_hash="$(md5sum <<< "$top_level_cmd_name" | awk '{print $1}')"

    eval "__bash_parse_cmd_top_level_cmd_${top_level_cmd_name_hash}_sub_commands+=(\$cmd_name)"
}

BAP_add_short_opt_help_text() {
    local usage="Usage is '${FUNCNAME[0]} <opt_letter> <help text>'"
    [ $# -ne 2 ] && __bash_parse_die "$0: line ${BASH_LINENO[0]}: $usage"
    local opt_letter=$1
    local help_text=$2

    __bash_parse_set_opt_help_text "$opt_letter" "$help_text" "${FUNCNAME[0]}"
}

BAP_generate_top_level_cmd_parser() {
    local usage="Usage is '${FUNCNAME[0]} <top_level_cmd_name>'"
    [ $# -ne 1 ] && __bash_parse_die "$0: line ${BASH_LINENO[0]}: $usage"
    local top_level_cmd_name=$1

    local top_level_cmd_name_hash

    top_level_cmd_name_hash="$(md5sum <<< "$top_level_cmd_name" | awk '{print $1}')"

    if ! [ -v "__bash_parse_cmd_top_level_cmd_${top_level_cmd_name_hash}_sub_commands" ]; then
        __bash_parse_die  "$0: line ${BASH_LINENO[0]}: (${FUNCNAME[0]}) must call 'BAP_set_top_level_cmd_name()' with a second argument of '$top_level_cmd_name' first!"
    fi

    local script=
    local help_text=
    local case_body=
    local opt_help_text=$'Options:\n'

    local name_of_parse_func=parse_top_level_args

    declare -n sub_cmd_array="__bash_parse_cmd_top_level_cmd_${top_level_cmd_name_hash}_sub_commands"
    for sub_cmd in "${sub_cmd_array[@]}"; do
        if ! [ -v "USAGE_TEXT_$sub_cmd" ]; then
            __bash_parse_die  "$0: line ${BASH_LINENO[0]}: (${FUNCNAME[0]}) must call 'BAP_generate_parse_func()' with an argument of '$sub_cmd' first!"
        fi
        eval "help_text+=\"  $top_level_cmd_name \\\$USAGE_TEXT_${sub_cmd}\"\$'\n'"
        case_body+="$sub_cmd) shift; if ! type -t \"$sub_cmd\" > /dev/null; then __bash_parse_die \"ERROR ($name_of_parse_func): no function named '$sub_cmd' to handle sub command '$sub_cmd'\"; fi; $sub_cmd \"\$@\";; "
    done

    
    opt_help_text+=$(__bash_parse_get_all_opt_help_text)

    help_text=$help_text$'\n'$opt_help_text
    case_body+="*) echo \"$help_text\" && exit 1;; "


    script+="$name_of_parse_func() { "
    script+="[ \$# -eq 0 ] && echo \"Usage:"$'\n'"$help_text\" && exit 1; "
    script+="case \"\$1\" in $case_body esac"
    script+=" }"

    __bash_parse_cmd_functions_to_export+=("$name_of_parse_func")

    eval "$script"
}

BAP_add_required_short_opt() {
    if [ $# -ne 3 ]; then
        __bash_parse_die "$(eval "echo -n \"\$0: line \${BASH_LINENO[0]}: $__bash_parse_add_short_opt_usage\"")"
    fi
    __bash_parse_add_opt "$@" required "${FUNCNAME[0]}"
}

BAP_add_optional_short_opt() {
    if [ $# -ne 3 ]; then
        __bash_parse_die "$(eval "echo -n \"\$0: line \${BASH_LINENO[0]}: $__bash_parse_add_short_opt_usage\"")"
    fi
    __bash_parse_add_opt "$@" optional "${FUNCNAME[0]}"
}

BAP_set_opt_arg_type() {
    if [ $# -ne 3 ]; then
        __bash_parse_die "$0: line ${BASH_LINENO[0]}: Usage is '${FUNCNAME[0]} <command> <opt_name> <opt_arg_type>'"
    fi

    local cmd_name=$1
    local opt_text=$2
    local opt_arg_type=$3

    __bash_parse_assert_defined "__bash_parse_cmd_$cmd_name" 'BAP_new_command()' "${FUNCNAME[0]}"

    eval "declare -n short_opt_array=__bash_parse_cmd_${cmd_name}_opts"

    __bash_parse_opt_is_defined "$cmd_name" "$opt_text" || \
        __bash_parse_die "$0: line ${BASH_LINENO[0]}: must call 'BAP_add_optional_short_opt()' or 'BAP_add_required_short_opt()' to define option '$opt_text'"

    case "$opt_arg_type" in
        existent_file)
            ;;
        *)
            __bash_parse_die "$0: line ${BASH_LINENO[0]}: opt arg type must be one of: [existent_file]"
            ;;
    esac

    __bash_parse_opt_set_arg_type "$cmd_name" "$opt_text" "$opt_arg_type"
}

########################################################################
# Main, if this library is called as an executable rather than sourced #
########################################################################

main() {
    local input_file=$1
    local output_file="$input_file.out"  
    local delete_shbang=no

    while IFS= read -r x; do
        eval "$x"
    done < <(sed -n '/^[[:space:]]*BAP/p' "$input_file")

    if [ -e "$output_file" ]; then
        rm "$output_file" || exit 1
    fi

    # so that we have the same permissions
    cp "$input_file" "$output_file"
    # Clear the contents
    true > "$output_file"

    local first_line
    first_line=$(head -n1 "$input_file")

    if [ "${first_line:0:2}" = '#!' ]; then
        delete_shbang=yes
        echo "$first_line"$'\n' >> "$output_file"
    fi

    for v in "${__bash_parse_cmd_variables_to_export[@]}"; do
        echo "declare -r $v='${!v}'" >> "$output_file"
    done

    echo >> "$output_file"

    for f in "${__bash_parse_cmd_functions_to_export[@]}"; do
        echo "$(declare -f "$f")"$'\n' >> "$output_file"
    done

    if [ "$delete_shbang" = yes ]; then
        tail -n+2 "$input_file"
    else
        cat "$input_file"
    fi | sed '/^[[:space:]]*BAP/d' >> "$output_file"
}

if [ "${BASH_SOURCE[-1]##*/}" = "bash_arg_parser" ]; then
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <input file name>"
        exit 1
    fi
    main "$@"
fi
